export const DONATIONS_REPOSITORY = 'DONATIONS_REPOSITORY';
export const DONATION_INFO_REPOSITORY = 'DONATION_INFO_REPOSITORY';
export const DONOR_TESTIMONIAL_REPOSITORY = 'DONOR_TESTIMONIAL_REPOSITORY';
